[dozer]
broker = "redis://127.0.0.1:6379"
result_backend = "redis://127.0.0.1:6379"
results_expire_in = 3600000
exchange = "machinery_exchange"
exchange_type ="direct"
default_queue ="machinery_tasks"
binding_key ="machinery_key"
